# AI YOUTH CAMP

### Hendrik Santoso Sugiarto, Ph.D.
### Calvin Institute of Technology


Tensor
---

Di Pytorch, tensor digunakan untuk input, output, dan parameter dari sebuah model
Tensor memiliki kelebihan dalam 2 hal:
1. Operasi Tensor dapat dihitung melalui GPU
2. Tensor dapat melakukan diferensiasi otomatis


In [1]:
import torch
import math
import numpy as np

Inisiasi sebuah Tensor
---

Tensor dapat diinisiasi melalui beragam cara

**Langsung dari data**

Tensor dapat diciptakan langsung dari data


In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

**Dari sebuah NumPy array**

Tensor dapat diciptakan langsung dari Numpy arrays (dan sebaliknya)



In [3]:
np_array = np.array(data)
print(np_array)
x_np = torch.from_numpy(np_array)
print(x_np)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


**Dari Tensor yang lain:**

Tensor yang baru akan memiliki sifat (shape, datatype) dari tensor sebelumnya, kecuali secara explicit diganti.



In [4]:
x_ones = torch.ones_like(x_data) # mempertahankan sifat x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # mengganti dtype x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7875, 0.2501],
        [0.6385, 0.4458]]) 



**Dari sebuah angka random atau konstanta:**

``shape`` adalah sebuah tuple dari dimensi tensor. Itu akan menentukan dimensi dari tensor output pada fungsi di bawah ini.



In [5]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9286, 0.3559, 0.5243],
        [0.5295, 0.0694, 0.4783]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


**Attribut Tensor**

Atribut Tensor akan menjelaskan bentuk, tipe data, dan perangkat penyimpanan tensor



In [6]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Tugas
----
Buatlah sebuah tensor 3x3: [[1,2,3],[4,5,6],[7,8,9]], lalu print ukuran tensornya

Operasi pada Tensor
-------
Terdapat lebih dari 100 operasi tensor (termasuk aritmatika, aljabar linear, manipulasi matriks, dan lainnya), dijelaskan secara lebih komprehensif

Setiap operasi ini dapat dioperasikan di GPU. Jika menggunakan Colab, alokasikan sebuah GPU melalui Runtime > Change runtime type > GPU

Secara bawaan, tensor diciptakan pada CPU. Kita harus memindahkan tensor ke GPU menggunakan metode ``.to`` (setelah memeriksa ketersediaan GPU). Memindahkan tensor besar antar perangkat, dapat memakan waktu dan memori yang banyak (jadi rencanakanlah secara hati-hati !!!)


In [7]:
if torch.cuda.is_available():
    print('Bisa GPU Cuda')
    tensor = tensor.to('cuda')
else:
    print('Hanya bisa CPU')

Hanya bisa CPU


In [8]:
tensor = tensor.to('mps')
tensor.device

RuntimeError: PyTorch is not linked with support for mps devices

Coba beberapa operasi dari daftar.



**Operasi standard yang mirip numpy untuk indexing dan slicing:**



In [9]:
tensor = torch.ones(4, 4)
print('Baris pertama: ', tensor[0])
print('Kolom pertama: ', tensor[:, 0])
print('Kolom terakhir:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

Baris pertama:  tensor([1., 1., 1., 1.])
Kolom pertama:  tensor([1., 1., 1., 1.])
Kolom terakhir: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Menyatukan beberapa tensor**

Gunakan ``torch.cat`` untuk concatenate beberapa tensor secara pilihan dimensi.
Alternatif lain, `torch.stack <https://pytorch.org/docs/stable/generated/torch.stack.html>`__,



In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)

**Operasi Aritmatika**



In [ ]:
# Menghitung perkalian matriks antara 2 tensors. y1, y2, y3 akan memiliki nilai yang sama
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
print(torch.matmul(tensor, tensor.T, out=y3))

# Menghitung perkalian elemen. z1, z2, z3 akan memiliki nilai yang sama
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
print(torch.mul(tensor, tensor, out=z3))

Tugas
----

Hitung perkalian matriks antara [[1,0],[0,1]] dengan dirinya sendiri, lalu tempelkan hasilnya dengan dirinya sendiri secara kolom dan baris sehingga menghasilkan matriks 4x4

Jembatan dengan Numpy
---

Tensor pada CPU dan Numpy array dapat menggunakan lokasi memori yang sama,
merubah yang satu akan merubah yang lain




Tensor menjadi NumPy array



In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

Perubahan pada tensor terjadi pada Numpy array.



In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

NumPy array menjadi Tensor



In [ ]:
n = np.ones(5)
print(f"n: {n}")
t = torch.from_numpy(n)
print(f"t: {t}")


Perubahan pada Numpy array terjadi pada Tensor.



In [ ]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

Tugas
---
Buatlah tensor sederhana 1x1: [[1]], lalu konversi menjadi numpy array, lalu konversi balik menjadi tensor

Matematika dan Logika dengan Tensor
----

In [ ]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

In [ ]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

Tugas
---
Hitung perkalian matriks antara [[1,0],[0,1]] dengan dirinya sendiri, lalu kuadratkan nilainya

Merubah Dimensi Tensor
----

In [ ]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

In [ ]:
a = torch.rand(20)
print(a.shape)
print(a)

a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

In [ ]:
a = torch.ones(4, 3, 2)
print(a.shape)
b = torch.rand(   3)     # perkalian a * b akan menghasilkan runtime error
print(b.shape)
c = b.unsqueeze(1)       # ubah menjadi 2-dimensional tensor, tambahkan dimensi baru
print(c.shape)
print(a * c)

In [ ]:
batch_me = torch.rand(3, 226, 226)
print(batch_me.shape)
batch_me.unsqueeze_(0)
print(batch_me.shape)

In [ ]:
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)

print(torch.reshape(output3d, (6 * 20 * 20,)).shape)

Tugas
---

Buatlah tensor 1x2x2: [[[1,1],[1,1]]], lalu buanglah bagian luar untuk menjadi bentuk tensor 2x2, lalu kembalikan ke bentuk tensor 1x2x2

Diferensiasi menggunakan Autograd
=======================================
PyTorch mempunyai mekanisme diferensiasi bawaan yang disebut dengan ``torch.autograd``. Mari kita lihat bagaimana ``autograd`` mengumpulkan gradien. Buat 2 tensor ``a`` dan ``b`` dengan
``requires_grad=True``. Ini memberi arahan bagi ``autograd`` bahwa setiap operasi terhadap tensor ini harus dilacak.




In [ ]:
import torch

x = torch.rand(5, 5)
y = torch.rand(5, 5)
z = torch.rand((5, 5), requires_grad=True)

a = x + y
print(f"Does `a` require gradients? : {a.requires_grad}")
b = x + z
print(f"Does `b` require gradients?: {b.requires_grad}")

In [ ]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
print(a)
print(b)

Kita membuat tensor lain ``Q`` dari ``a`` dan ``b``.

\begin{align}Q = 3a^3 - b^2\end{align}



In [ ]:
Q = 3*a**3 - b**2
Q

Aumsikan ``a`` dan ``b`` sebagai parameter dari NN, dan ``Q`` eror. Di proses pelatihan NN, kita ingin gradien dari eror terhadap parameter, dimana:

\begin{align}\frac{\partial Q}{\partial a} = 9a^2\end{align}

\begin{align}\frac{\partial Q}{\partial b} = -2b\end{align}


Ketika kita memanggil ``.backward()`` pada ``Q``, autograd menghitung gradien ini dan. menyimpannya dalam atribut ``.grad`` dari tensor tersebut.

Kita harus menggunakan argumen ``gradient`` di ``Q.backward()`` karena ini adalah sebuah vektor. ``gradient`` adalah sebuah tensor dari bentuk yang sama dengan ``Q``, dan merepresentasikan gradien dari Q terhadap dirinya sendiri, dimana:

\begin{align}\frac{dQ}{dQ} = 1\end{align}

Kita dapat pula agregasi Q menjadi sebuah skalar dan memanggil backward secara implisit, seperti ``Q.sum().backward()``.




In [ ]:
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

Gradien sekarang telah disimpan dalam ``a.grad`` dan ``b.grad``



In [ ]:
# cek apakah gradien yang tersimpan terhitung benar
print(9*a**2 == a.grad)
print(-2*b == b.grad)

Tugas
----------
Buatlah loss function sebagai berikut:
\begin{align}Y = \Sigma  ln(x) \end{align}

Gunakan autograd untuk menghitung gradiennya terhadap parameter a

Hitung turunannya secara analitik dan bandingkan

In [ ]:
x =
Y =
# backward pass



Diferensiasi Neural Network Otomatis melalui ``torch.autograd``
=======================================

Algoritma untuk melatih neural networks adalah **back propagation**. Pada algoritma ini, parameters (bobot) akan diubah sesuai dengan **gradient** dari loss function terhadap parameter tersebut.

Untuk menghitung gradient itu, PyTorch mempunyai mekanisme diferensiasi bawaan yang disebut dengan ``torch.autograd``. Ini mempermudah perhitungan gradien secara otomatis terhadap computational graph jenis apapun.

Cobalah 1-layer neural network, dengan input  ``x``,parameters ``w`` and ``b``, dan loss function sebagai berikut:


In [ ]:
import torch

x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)
loss

Tugas
-----

Hitung binary cross entropy alternatif dengan menggunakan operasi tensor

In [ ]:
def BCE(z, y):
    p =
    return p.mean()

loss_manual = BCE(z,y)
loss_manual

Tensor dan Gradien
------------------------------------------

pada network ini, ``w`` dan ``b`` adalah **parameters**, yang akan kita optimalisasi.
Maka, kita memerlukan perhitungan gradien dari sebuah loss function terhadap variabel-variabel tersebut. Untuk bisa melakukannya, kita mengatur ``requires_grad`` dari tensor-tensor tersebut.



Sebuah fungsi yang kita aplikasikan ke tensor sebagai kontruksi computational graph adalah sebuah kelas objek ``Function``. Objek ini mengerti bagaimana cara menghitung fungsi dalam arah *forward*, dan juga bagaimana cara menghitung turunannya selama langkah-langkah *backward propagation*. Sebuah referensi terhadap fungsi backward propagation disimpan dalam properti ``grad_fn`` dari sebuah tensor. Kamu dapat menemukan informasi lebih lanjut mengenai ``Function`` dalam dokumentasi berikut
https://pytorch.org/docs/stable/autograd.html#function


In [ ]:
print('Gradient function for z =', z.grad_fn)
print('Gradient function for loss =', loss.grad_fn)

Menghitung Gradien
-------------------

Untuk optimalisasi bobot pada neural network, kita perlu menghitung turunan dari loss function terhadap parameter. Secara khusus, kita memerlukan $\frac{\partial loss}{\partial w}$ dan
$\frac{\partial loss}{\partial b}$ terhadap nilai dari ``x`` and ``y``. Untuk menghitung turunan itu, kita memanggil ``loss.backward()``, lalu mendapatkan nilai ``w.grad`` dan
``b.grad``:



In [ ]:
loss.backward()
print(w.grad)
print(b.grad)



Mematikan Pelacakan Gradien
---------------------------

Secara bawaan, semua tensor dengan ``requires_grad=True`` akan melacak sejarah komputasi dan mendukung komputasi gradien. Tetapi, terdapat beberapa kasus dimana kita tidak perlu melakukannya. Misalnya ketika kita melatih model dan hanya ingin menggunakannya terhadap beberapa input data, kita hanya perlu melakukan komputasi *forward*. Kita bisa berhenti melacak komputasi dengan menggunakan blok ``torch.no_grad()``.



In [ ]:
z = torch.matmul(x, w)+b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w)+b
print(z.requires_grad)

Cara lain untuk memperoleh hasil yang sama adalah dengan menggunakan metode ``detach()`` pada tensor:




In [ ]:
z = torch.matmul(x, w)+b
z_det = z.detach()
print(z_det.requires_grad)

Ada alasan lain untuk mematikan pelacakan gradien:
    - Untuk menandai beberapa parameter di neural network sebagai **frozen parameters**. Ini skenario yang sangat umum untuk `finetuning a pretrained network` https://pytorch.org/tutorials/beginner/finetuning_torchvision_models_tutorial.html
    - Untuk mempercepat perhitungan ketika hanya menghitung gerakan forward, karena komputasi pada tensors tanpa pelacakan gradien akan jauh lebih efisien
    

Tugas
---
Cobalah proses diatas dengan persamaan lain

Neural Network
===================

Neural networks terdiri dari lapisan (layers) dan modul (modules) yang beroperasi pada data.
Semua keterangan mengenai bagian penyusunnya dapat dibaca di torch.nn https://pytorch.org/docs/stable/nn.html  
Sebuah neural network adalah sebuah modul yang terdiri dari modul-modul lainnya (layers). Struktur berlapis ini dipakai untuk memudahkan manajemen arsitektur kompleks

Di bagian ini, kita akan menciptakan neural network untuk klasifikasi gambar pada dataset FashionMNIST.




In [ ]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
#import torchvision
#from torchvision import datasets, transforms

Memilih Perangkat untuk Training
-----------------------
Kita akan melatih model pada perangkat akselerasi seperti GPU (jika tersedia)
Jika tidak tersedia kita akan melanjutkan dengan menggunakan CPU.



In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Gunakan perangkat {device}')

Definisikan Kelas
-------------------------
Kita mendefinisikan neural network melalui ``nn.Module``, dan menginisiasi lapisan neural network di ``__init__``. Setiap ``nn.Module`` mengimplementasikan operasi pada input melalui metode ``forward``



In [ ]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 3),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        pred_probab = nn.Softmax(dim=1)(logits)
        return pred_probab

Ciptakan sebuah salinan (instance) dari ``NeuralNetwork``, dan pindahkan menuju ``device``, dan tampilkan strukturnya.



In [ ]:
model = NeuralNetwork().to(device)
print(model)

Untuk menggunakan model, kita memasukan inputnya. Ini mengeksekusi ``forward``,
bersama `background operations` Jangan memanggil ``model.forward()`` secara langsung!

Memanggil model pada input menghasilkan tensor 10 dimensi dengan nilai prediksi untuk setiap kelas.
Kita mendapatkan peluang prediksi dengan memasukannya melalui salinan (instance) dari modul ``nn.Softmax``.



In [ ]:
X = torch.rand(1, 28, 28, device=device)
pred_probab = model(X)
y_pred = pred_probab.argmax(1)
print(f"Prediksi: {y_pred}")

Lapisan Model
-------------------------

Mari memecah lapisan-lapisan pada model. Untuk ilustrasi, kita coba ambil sampel minibatch dari 3 gambar dengan ukuran 28x28 dan lihat apa yang terjadi ketika kita memasukannya melalui network.


In [ ]:
input_image = torch.rand(3,28,28)
print(input_image.size())

Perataan (Flatten)
---------------

Kita menginisasi lapisan perataan
untuk mengubah setiap gambar 2D 28x28 menjadi vektor 784 pixel.



In [ ]:
flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())

Transformasi Linear
-----------

Lapisan linear
adalah modul yang mengerjakan transformasi linear pada input dengan menggunakan bobot yang sudah disimpan




In [ ]:
layer1 = nn.Linear(in_features=28*28, out_features=20)
hidden1 = layer1(flat_image)
print(hidden1.size())

Fungsi Aktivasi
----------
Aktivasi non-linear akan membuat map kompleks dari input menuju output.
Non-linearitas akan membantu neural network belajar beragam variasi fenomena.

Pada contoh kali ini, kita hanya menggunakan `nn.ReLU`
diantara lapisan linear, tapi terdapat bentuk aktivasi non-linear lain.



In [ ]:
print(f"Before ReLU: {hidden1}\n\n")
hidden1 = nn.ReLU()(hidden1)
print(f"After ReLU: {hidden1}")

Bentuk Berderet
-------------

`nn.Sequential` adalah sebuah modul dengan susunan deretan modul. Data diolah melalui semua modul sesuai urutan yang diberikan.



In [ ]:
layer2 = nn.Linear(20, 10)
actf = nn.ReLU()

seq_modules = nn.Sequential(
    flatten,
    layer1,
    actf,
    layer2
)
input_image = torch.rand(3,28,28)
logits = seq_modules(input_image)
logits

Bentuk Tensor (Alternatif)
-------------

Neural network dapat pula disusun sesuai deretan operasi tensor dari input menuju output



Tugas
----
Lanjutkan operasi tensor berikut untuk menghasilkan logits yang sama dengan bentuk sequential

Softmax
---------------

Lapisan paling akhir pada model kita mengeluarkan `logits` - nilai diantara [-\infty, \infty] - sebagai input dari modul
`nn.Softmax`_. Hasilnya adalah nilai diantara
[0, 1] sebagai representasi peluang prediksi untuk setiap kelas. parameter ``dim`` mengindikasikan pilihan dimensi mana yang jumlahnya harus 1.



In [ ]:
softmax = nn.Softmax(dim=1)
pred_probab = softmax(logits)
pred_probab

Parameter Model
-------------------------
Banyak lapisan dalam neural network adalah parameter, yaitu memiliki bobot yang akan dioptimalisasi selama training
``nn.Module`` otomatis melacak semua isi dalam objek model, dan membuat semua parameter terakses menggunakan metode ``parameters()`` atau ``named_parameters()``.

Di contoh ini, kita iterasi setiap parameter, lalu mencetak ukurannya dan melihat nilainya.




In [ ]:
print("Model structure: ", model, "\n\n")

for name, param in model.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n")

Tugas
---
Buatlah kelas neural network baru yang sama persis dengan kelas sebelumnya namun menggunakan bentuk tensor

In [ ]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.layer1 = nn.Linear(28*28, 512)
        self.layer2 = nn.Linear(512, 512)
        self.layer3 = nn.Linear(512, 3)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.flatten(x)
        x =
        x =
        x =
        x =
        logits =
        prob = nn.Softmax(dim=1)(logits)
        return prob

NNet = NeuralNetwork().to(device)
print(NNet)

Tugas
---
Buatlah perceptron 3 input dan 1 output

Tugas
---
Buatlah multi-layer perceptron 3 input, 1 hidden layer (3 neurons), dan 1 output

Klasifikasi Gambar
----------------------------

#### Mengunduh CIFAR10



In [ ]:
import torch
import torchvision
import torchvision.transforms as transforms

Unduh cifar10 dataset (yang berisi 60000 gambar kecil beserta labelnya), lalu gunakan transformasi data untuk merubah ke bentuk tensor minibatch yang masing-masing berisi 8 gambar
Output dari torchvision dataset adalah PILImage antara [0, 1].
Transformasi menjadi tensor dengan rentang antara [-1, 1].



In [ ]:
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

batch_size = 8

trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=batch_size,
                                          shuffle=True, num_workers=2)

testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=batch_size,
                                         shuffle=False, num_workers=2)

classes = ('plane', 'car', 'bird', 'cat',
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

Cek beberapa gambar

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# functions to show an image


def imshow(img):
    img = img / 2 + 0.5     # unnormalize
    npimg = img.numpy()
    plt.imshow(np.transpose(npimg, (1, 2, 0)))
    plt.show()


# get some random training images
dataiter = iter(trainloader)
images, labels = dataiter.next()

print(images.shape)
print(images)

# show images
imshow(torchvision.utils.make_grid(images))
# print labels
print(' '.join(f'{classes[labels[j]]:5s}' for j in range(batch_size)))

Tugas
---
Buat 3 linear layer untuk meneruskan convolutional layer berikut (kali ini inputnya memiliki 3-channel)



In [ ]:
import torch.nn as nn
import torch.nn.functional as F


class CovNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x =
        return x


covnet = CovNet()

Optimisasi
----
Gunakan cross-entropy dan SGD dengan momentum.



In [ ]:
import torch.optim as optim

criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(covnet.parameters(), lr=0.001, momentum=0.9)

Tugas
---
Ambil data dari iterator dalam bentuk MiniBatch, masukan menjadi input, dan optimisasi sebanyak 5 epoch.
Tampilkan nilai dari akumulasi loss untuk memastikan optimisasi berjalan dengan baik. Lalu plot nilai loss dan hitung total waktu yang dibutuhkan.



In [ ]:
import time
start = time.time()

Loss = []
for epoch in range(5):  # loop over the dataset multiple times

    running_loss = 0.0
    for i, data in enumerate(trainloader):
        # get the inputs; data is a list of [inputs, labels]
        inputs, labels = data

        # zero the parameter gradients

        # forward + backward + optimize

        # print statistics
        running_loss += loss.item()

    print(f'[{epoch + 1}] loss: {running_loss / (i+1)}')
    Loss.append(running_loss / (i+1))

plt.plot(Loss)
end = time.time()
print('Finished Training, time: %f'%(end-start))



Simpan model yang sudah dilatih



In [ ]:
torch.save(covnet.state_dict(), 'cifar_covnet.pth')

### Tes

Setelah melatih beberapa epoch pada training dataset, cek apakah model sudah mempelajari sesuatu.
Kita akan cek dengan memprediksi output dan membandingkan dengan labelnya. Jika prediksi benar, kita tambah sampel pada daftar prediksi benar.




In [ ]:
dataiter = iter(testloader)
images, labels = dataiter.next()

# print images
imshow(torchvision.utils.make_grid(images))
print('GroundTruth: ', ' '.join(f'{classes[labels[j]]:5s}' for j in range(8)))

Load model yang telah disimpan


In [ ]:
covnet = CovNet()
covnet.load_state_dict(torch.load('cifar_covnet.pth'))

Coba model pada contoh berikut



In [ ]:
outputs = covnet(images)

In [ ]:
_, predicted = torch.max(outputs, 1)

print('Prediksi: ', ' '.join(f'{classes[predicted[j]]:5s}'
                              for j in range(8)))

Cek performa pada seluruh test dataset

In [ ]:
correct = 0
total = 0
# since we're not training, we don't need to calculate the gradients for our outputs
with torch.no_grad():
    for data in testloader:
        images, labels = data
        # calculate outputs by running images through the network
        outputs = covnet(images)
        # the class with the highest energy is what we choose as prediction
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f'akurasi pada tes: {100 * correct // total} %')

Manakah kelas dengan performa baik dan tidak baik?


In [ ]:
# prepare to count predictions for each class
correct_pred = {classname: 0 for classname in classes}
total_pred = {classname: 0 for classname in classes}

# again no gradients needed
with torch.no_grad():
    for data in testloader:
        images, labels = data
        outputs = covnet(images)
        _, predictions = torch.max(outputs, 1)
        # collect the correct predictions for each class
        for label, prediction in zip(labels, predictions):
            if label == prediction:
                correct_pred[classes[label]] += 1
            total_pred[classes[label]] += 1


# print accuracy for each class
for classname, correct_count in correct_pred.items():
    accuracy = 100 * float(correct_count) / total_pred[classname]
    print(f'akurasi untuk label: {classname:5s} adalah {accuracy:.1f} %')

Menggunakan GPU
----------------

cek apakah perangkat cuda sudah tersedia?

baik data maupun model harus di kirim ke perangkat cuda terlebih dahulu

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Assuming that we are on a CUDA machine, this should print a CUDA device:

print(device)

Tugas
---
Coba gunakan model berikut pada GPU dan bandingkan latensinya dengan CPU



In [ ]:
import time

covnet = CovNet().to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(covnet.parameters(), lr=0.001, momentum=0.9)

start = time.time()

Loss = []
for epoch in range(5):  # loop over the dataset multiple times

    running_loss = 0.0
    for i, data in enumerate(trainloader):
        # get the inputs; data is a list of [inputs, labels]
        inputs, labels = data

        # zero the parameter gradients

        # forward + backward + optimize

        # print statistics
        running_loss += loss.item()

    print(f'[{epoch + 1}] loss: {running_loss / (i+1)}')
    Loss.append(running_loss / (i+1))

plt.plot(Loss)
end = time.time()
print('Finished Training, time: %f'%(end-start))


end = time.time()
print(end-start)

Tugas
---
Bandingkan optimisasi SGD dan Adam

Untuk dokumentasi bisa dilihat disini https://pytorch.org/docs/stable/optim.html


### SGD

In [ ]:
covnet = CovNet().to(device)
criterion = nn.CrossEntropyLoss()
optimizer =

start = time.time()

Loss = []
for epoch in range(5):  # loop over the dataset multiple times

    running_loss = 0.0
    for i, data in enumerate(trainloader):
        # get the inputs; data is a list of [inputs, labels]
        inputs, labels = data

        # zero the parameter gradients
        optimizer.zero_grad()

        # forward + backward + optimize
        outputs = covnet(inputs.to(device))
        loss = criterion(outputs, labels.to(device))
        loss.backward()
        optimizer.step()

        # print statistics
        running_loss += loss.item()

    print(f'[{epoch + 1}] loss: {running_loss / (i+1)}')
    Loss.append(running_loss / (i+1))

plt.plot(Loss)
end = time.time()
print('Finished Training, time: %f'%(end-start))


end = time.time()
print(end-start)

### Adam

In [ ]:
covnet = CovNet().to(device)
criterion = nn.CrossEntropyLoss()
optimizer =

start = time.time()

Loss = []
for epoch in range(5):  # loop over the dataset multiple times

    running_loss = 0.0
    for i, data in enumerate(trainloader):
        # get the inputs; data is a list of [inputs, labels]
        inputs, labels = data

        # zero the parameter gradients
        optimizer.zero_grad()

        # forward + backward + optimize
        outputs = covnet(inputs.to(device))
        loss = criterion(outputs, labels.to(device))
        loss.backward()
        optimizer.step()

        # print statistics
        running_loss += loss.item()

    print(f'[{epoch + 1}] loss: {running_loss / (i+1)}')
    Loss.append(running_loss / (i+1))

plt.plot(Loss)
end = time.time()
print('Finished Training, time: %f'%(end-start))


end = time.time()
print(end-start)

Hitung kembali akurasi

In [ ]:
correct = 0
total = 0
covnet.to('cpu')
# prepare to count predictions for each class
correct_pred = {classname: 0 for classname in classes}
total_pred = {classname: 0 for classname in classes}

# again no gradients needed
with torch.no_grad():
    for data in testloader:
        images, labels = data
        outputs = covnet(images)
        _, predictions = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predictions == labels).sum().item()

        # collect the correct predictions for each class
        for label, prediction in zip(labels, predictions):
            if label == prediction:
                correct_pred[classes[label]] += 1
            total_pred[classes[label]] += 1

print(f'akurasi pada seluruh data tes: {100 * correct // total} %')

# print accuracy for each class
for classname, correct_count in correct_pred.items():
    accuracy = 100 * float(correct_count) / total_pred[classname]
    print(f'akurasi untuk label: {classname:5s} adalah {accuracy:.1f} %')